import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Board } from "~/Components/board";
import Image from "next/image";
import { motion } from "framer-motion";
import Arknight1 from "../stock/arknight1.jpeg";
import Arknight2 from "../stock/arknight2.jpeg";
import Arknight3 from "../stock/arknight3.jpeg";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Board />
      <div id="content" className="flex flex-col gap-6 p-16">
        {/* <div className="h-full w-full border border-red-400">test</div> */}
        <motion.div
          className={`flex w-full flex-col items-center justify-center lg:flex-row`}
          initial={{ opacity: 0, x: -100 }}
          whileInView={{ opacity: 1, x: 0 }}
        >
          <div className="relative h-[22rem] w-full rounded-xl lg:h-[22rem] lg:w-[40%]">
            <Image
              className="object-cover"
              src={Arknight1}
              alt="figure 1"
              fill
            />
          </div>

          <div className="w-full gap-2 bg-base-100 p-4 lg:w-[60%]">
            <h2 className="text-3xl text-primary">
              <a href="#">What is DaisyUI</a>
            </h2>
            {/* Add horizontal line */}
            <div className="divider"></div>
            <p className="overflow-hidden truncate whitespace-normal text-justify text-lg">
              There are two main goals of quantum communication. On one hand is
              to provide a means for quantum devices to share quantum states
              directly among each other without being translated and carried by
              classical communication media. This development will bring out the
              full potential of quantum computing and measurement devices,
              similar to how the internet did for digital devices. On the other
              hand, quantum principles such as entanglement and superposition
              provide new ways to generate secret keys and secure many
              communication tasks unachievable by their digital counterparts.
            </p>
            <div className="card-actions justify-end">
              <Link
                className="btn-ghost btn whitespace-normal text-primary"
                href="#"
              >
                Read more
              </Link>
            </div>
          </div>
        </motion.div>

        <motion.div
          className={`flex w-full flex-col items-center justify-center lg:flex-row-reverse`}
          initial={{ opacity: 0, x: -100 }}
          whileInView={{ opacity: 1, x: 0 }}
        >
          <div className="relative h-[22rem] w-full rounded-xl lg:h-[22rem] lg:w-[40%]">
            <Image
              className="object-cover"
              src={Arknight2}
              alt="figure 1"
              fill
            />
          </div>

          <div className="w-full gap-2 bg-base-100 p-4 lg:w-[60%]">
            <h2 className="text-3xl text-primary">
              <a href="#">Quick start</a>
            </h2>
            {/* Add horizontal line */}
            <div className="divider"></div>
            <p className="overflow-hidden truncate whitespace-normal text-justify text-lg">
              There are two main goals of quantum communication. On one hand is
              to provide a means for quantum devices to share quantum states
              directly among each other without being translated and carried by
              classical communication media. This development will bring out the
              full potential of quantum computing and measurement devices,
              similar to how the internet did for digital devices. On the other
              hand, quantum principles such as entanglement and superposition
              provide new ways to generate secret keys and secure many
              communication tasks unachievable by their digital counterparts.
            </p>
            <div className="card-actions justify-end">
              <Link
                className="btn-ghost btn whitespace-normal text-primary"
                href="#"
              >
                Read more
              </Link>
            </div>
          </div>
        </motion.div>

        <motion.div
          className={`flex w-full flex-col items-center justify-center lg:flex-row`}
          initial={{ opacity: 0, x: -100 }}
          whileInView={{ opacity: 1, x: 0 }}
        >
          <div className="relative h-[22rem] w-full rounded-xl lg:h-[22rem] lg:w-[40%]">
            <Image
              className="object-cover"
              src={Arknight3}
              alt="figure 1"
              fill
            />
          </div>

          <div className="w-full gap-2 bg-base-100 p-4 lg:w-[60%]">
            <h2 className="text-3xl text-primary">
              <a href="#">About us</a>
            </h2>
            {/* Add horizontal line */}
            <div className="divider"></div>
            <p className="overflow-hidden truncate whitespace-normal text-justify text-lg">
              There are two main goals of quantum communication. On one hand is
              to provide a means for quantum devices to share quantum states
              directly among each other without being translated and carried by
              classical communication media. This development will bring out the
              full potential of quantum computing and measurement devices,
              similar to how the internet did for digital devices. On the other
              hand, quantum principles such as entanglement and superposition
              provide new ways to generate secret keys and secure many
              communication tasks unachievable by their digital counterparts.
            </p>
            <div className="card-actions justify-end">
              <Link
                className="btn-ghost btn whitespace-normal text-primary"
                href="#"
              >
                Read more
              </Link>
            </div>
          </div>
        </motion.div>
      </div>
    </>
  );
};

export default Home;
